namespace Api.DTOs;

public record ComprobanteDto(
    int Id,
    string Categoria,
    DateTime Fecha,
    string Tipo,
    int PuntoDeVenta,
    long NumeroDesde,
    long NumeroHasta,
    long? CodAutorizacion,
    string? ContraparteTipoDoc,
    long? ContraparteNroDoc,
    string? ContraparteDenominacion,
    decimal TipoCambio,
    string Moneda,
    decimal? NetoGravIva0,
    decimal? Iva25,
    decimal? NetoGravIva25,
    decimal? Iva5,
    decimal? NetoGravIva5,
    decimal? Iva105,
    decimal? NetoGravIva105,
    decimal? Iva21,
    decimal? NetoGravIva21,
    decimal? Iva27,
    decimal? NetoGravIva27,
    decimal? PercIva,
    decimal? PercOtrosImp,
    decimal? PercIIBB,
    decimal? PercImpMuni,
    decimal? ImpInterno,
    decimal? NoGravado,
    decimal? OtrosTributos,
    decimal? ImporteTotal
);

public record SaveComprobanteRequest(
    string Categoria,
    DateTime Fecha,
    string Tipo,
    int PuntoDeVenta,
    long NumeroDesde,
    long NumeroHasta,
    long? CodAutorizacion,
    string? ContraparteTipoDoc,
    long? ContraparteNroDoc,
    string? ContraparteDenominacion,
    decimal TipoCambio,
    string Moneda,
    decimal? NetoGravIva0,
    decimal? Iva25,
    decimal? NetoGravIva25,
    decimal? Iva5,
    decimal? NetoGravIva5,
    decimal? Iva105,
    decimal? NetoGravIva105,
    decimal? Iva21,
    decimal? NetoGravIva21,
    decimal? Iva27,
    decimal? NetoGravIva27,
    decimal? PercIva,
    decimal? PercOtrosImp,
    decimal? PercIIBB,
    decimal? PercImpMuni,
    decimal? ImpInterno,
    decimal? NoGravado,
    decimal? OtrosTributos,
    decimal? ImporteTotal
);

public record BulkDeleteRequest(List<int> Ids);
